# https://jupyterbook.org/customize/config.html

title: "Changran Zhang's Portfolio"
author: Changran Zhang

# 只构建目录里出现的文件
only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*

execute:
  execute_notebooks: "off"  # 先关闭执行，后续需要再打开

sphinx:
  config:
    myst_heading_anchors: 4
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
    